"""Initialize pymfdata sample app entities..

Revision ID: 211228182104
Revises: 
Create Date: 2021-12-28 18:21:04.937739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211228182104'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('memo',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='Memo ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Memo Title'),
    sa.Column('content', sa.Text(), nullable=True, comment='Memo body := content'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memo_labels',
    sa.Column('memo_id', sa.BigInteger(), nullable=False),
    sa.Column('label_name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['label_name'], ['label.name'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['memo_id'], ['memo.id'], ),
    sa.PrimaryKeyConstraint('memo_id', 'label_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memo_labels')
    op.drop_table('memo')
    op.drop_table('label')
    # ### end Alembic commands ###
